services:
  app:
    image: ishee/appointment-service-app:latest
    container_name: appointment-service-app-container
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 87363699
      DB_NAME: isheecrm
    ports:
      - "8080:8080"
    networks:
      - appointment-service_app-network
    depends_on:
      - postgres

networks:
  appointment-service_app-network:
    external: true
