services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 87363699
      POSTGRES_DB: isheecrm
    volumes:
      - isheecrm_isheecrm_data:/var/lib/postgresql/data
    networks:
      - appointment-service_app-network
    ports:
      - "5432:5432"

  app:
    image: ishee/appointment-service-app:latest
    container_name: appointment-service-app-container
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 87363699
      DB_NAME: isheecrm
    ports:
      - "8080:8080"
    networks:
      - appointment-service_app-network
    depends_on:
      - postgres

networks:
  appointment-service_app-network:
    driver: bridge

volumes:
  isheecrm_isheecrm_data:
    external: true   # Указываем, что том является внешним